# Deploy Jenkins DevOps container locally

version: '3.2'

services:
  jenkins-devops:
    image: garystafford/jenkins-devops:2017.10.07
    hostname: jenkins
    ports:
    - "8083:8080/tcp"
    - "50000:50000/tcp"
    networks:
    - demo_overlay_net
    volumes:
    - /tmp/jenkins_home:/var/jenkins_home
    - /tmp/backup/hudson:/tmp/backup/hudson
    # - /var/run/docker.sock:/var/run/docker.sock

networks:
  demo_overlay_net:
